# Itertools in Python 3, By Example

***

<p>According to the itertools docs, itertools it is a module that implements a number of iterator building blocks inspired by constructs from APL, Haskell, and SML...Together, they form an 'iterator algebra' making it possible to construct specialized tools succinctly and efficiently in pure Python.</p>

### built-in zip()

In [61]:
list(zip([1, 2, 3], ['a', 'b', 'c']))

[(1, 'a'), (2, 'b'), (3, 'c')]

### iter() returns an iterator object for that iterable

In [62]:
iter([1, 2, 3, 4])

### map() is another iterator operator that, applies a single-parameter function to each element of an iterable one element at a time

In [63]:
list(map(len, ['abc', 'de', 'fghi']))

[3, 2, 4]

Since iterators are iterable, you can compose zip() and map() to produce an iterator over combinations of elements in more than one iterable. For example, the following sums corresponding elements of two lists:

In [64]:
list(map(sum, zip([1, 2, 3], [4, 5, 6])))

[5, 7, 9]

The better_grouper() function is better for a couple of reasons. First, without the reference to the len() built-in, better_grouper() can take any iterable as an argument (even infinite iterators). Second, by returning an iterator rather than a list, better_grouper() can process enormous iterables without trouble and uses much less memory.

### grouper
The problem with better_grouper() is that it doesn’t handle situations where the value passed to the second argument isn’t a factor of the length of the iterable in the first argument:

In [65]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list(nums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

The elements 9 and 10 are missing from the grouped output. This happens because zip() stops aggregating elements once the shortest iterable passed to it is exhausted. It would make more sense to return a third group containing 9 and 10.

To do this, you can use itertools.zip_longest(). This function accepts any number of iterables as arguments and a fillvalue keyword argument that defaults to None. The easiest way to get a sense of the difference between zip() and zip_longest() is to look at some example output:

In [66]:
import itertools as it
x = [1, 2, 3, 4, 5]
y = ['a', 'b', 'c']
list(zip(x, y))
[(1, 'a'), (2, 'b'), (3, 'c')]
list(it.zip_longest(x, y))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, None), (5, None)]

With this in mind, replace zip() in better_grouper() with zip_longest():

In [67]:
import itertools as it


def grouper(inputs, n, fillvalue=None):
    iters = [iter(inputs)] * n
    return it.zip_longest(*iters, fillvalue=fillvalue)

Now you get a better result:

In [68]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(list(grouper(nums, 4)))

[(1, 2, 3, 4), (5, 6, 7, 8), (9, 10, None, None)]


### product()

In [69]:
list(it.product([1, 2], ['a', 'b']))

[(1, 'a'), (1, 'b'), (2, 'a'), (2, 'b')]

# Permutation
***


Another “brute force” itertools function is permutations(), which accepts a single iterable and produces all possible permutations (rearrangements) of its elements:

In [70]:
import itertools as it

list(it.permutations(['a', 'b', 'c']))

[('a', 'b', 'c'),
 ('a', 'c', 'b'),
 ('b', 'a', 'c'),
 ('b', 'c', 'a'),
 ('c', 'a', 'b'),
 ('c', 'b', 'a')]

In [71]:
N=3
L=list(range(N))
L #show

[0, 1, 2]

In [72]:
for p in it.permutations(L):
    print(p)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


# Matrices in Numpy
***


In [73]:
import numpy as np

N=3
M= np.arange(N**2)
M #show

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
type(M)

numpy.ndarray

In [75]:
#reshape
N=3
M= np.arange(N**2).reshape((N,N))
M #show

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
#FIrst row
M[0]

array([0, 1, 2])

In [77]:
#Second Row, third column
M[1,2]

5

In [78]:
#Second Row, third column
M[(1, 2)]

5

In [79]:
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
#First column
M[:, 0]

array([0, 3, 6])

In [81]:
#Bottom right four entries
M[1:,1:]

array([[4, 5],
       [7, 8]])

In [82]:
#Permute the rows - note the list
M[[1,2,0]]

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [83]:
#Permute the columns
M[:, [1,2,0]]

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

# Generate All MAtrices
***

In [84]:
# N
N = 3

# Square matrix with N rows, N columns.
# Entries are [0, 1, 2, ..., N-1] in order.
M = np.arange(N**2).reshape((N,N))

# Show.
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
# Generate all permutations of N indices from 0.
for p in it.permutations(range(N)):
  print(p)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


In [86]:
# Generate all permutations of rows of M.
for p in it.permutations(range(N)):
  print(M[list(p)])
  print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [6 7 8]
 [3 4 5]]

[[3 4 5]
 [0 1 2]
 [6 7 8]]

[[3 4 5]
 [6 7 8]
 [0 1 2]]

[[6 7 8]
 [0 1 2]
 [3 4 5]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]



In [87]:
# Generate all permutations of columns of M.
for p in it.permutations(range(N)):
  print(M[:, list(p)])
  print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 2 1]
 [3 5 4]
 [6 8 7]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]

[[1 2 0]
 [4 5 3]
 [7 8 6]]

[[2 0 1]
 [5 3 4]
 [8 6 7]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]



# Identity matrix
***

In [88]:
# N.
N = 3

# The NxN identity matrix.
np.eye(N)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
# The NxN identity matrix with integers.
np.eye(N, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [90]:
# The NxN identity matrix with integers.
I = np.eye(N, dtype=int)

In [91]:
# Generate all possible permutations of rows of I.
for p in it.permutations(range(N)):
  print(I[list(p)])
  print()

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 0 0]
 [0 0 1]
 [0 1 0]]

[[0 1 0]
 [1 0 0]
 [0 0 1]]

[[0 1 0]
 [0 0 1]
 [1 0 0]]

[[0 0 1]
 [1 0 0]
 [0 1 0]]

[[0 0 1]
 [0 1 0]
 [1 0 0]]

