## NumPy

***

Array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

### `ndarray.ndim`
the number of axes (dimensions) of the array.

### `ndarray.shape`
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

### `ndarray.size`
the total number of elements of the array. This is equal to the product of the elements of shape.

### `ndarray.dtype`
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

### `ndarray.itemsize`
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

### `ndarray.data`
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [4]:
x = [1,2,3,4]
x[::-1] # :start point, :end point and -1 step

[4, 3, 2, 1]

In [5]:
# Permutations 
import itertools as it

In [6]:
list(range(2,10,3)) #the number 3 could read as i + 3

[2, 5, 8]

In [7]:
# N - could be a vertices
N = 3

# A list of integer up to N
L = list(range(N))

# Show
L

[0, 1, 2]

In [8]:
#generate all the permutations
for p in it.permutations(L):
    print(p)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


In [9]:
N = 5

# 
M = np.arange(N**2) #n raised to the power of 2
#show
M

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
# rewrite as 3x3 matrix
N = 3

# 
M = np.arange(N**2).reshape((N,N))
#show
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#first row
M[0]

array([0, 1, 2])

In [12]:
# element second, row first column
M[1,2]

5

In [13]:
# first column
M[:, 0] # o means first of the column. : means everything and the 0 is the first element

array([0, 3, 6])

In [14]:
# second and third rows
M[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [15]:
# Bottom right four entries
M[1:,1:]

array([[4, 5],
       [7, 8]])

In [16]:
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
#swap the rows
M[[2,1,0]]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [18]:
#swap the columns
M[:, [2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [19]:
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
S = "Hello, World!"

In [21]:
# Slicing
S[:2]


'He'

In [22]:
S[2:6] # start point and end point. 2 is included and 6th is not included

'llo,'

In [23]:
S[1::2]

'el,Wrd'

In [24]:
K = [1 ,2, 3]

In [25]:
#generate all the permutations
for p in it.permutations(K):
    print(p)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)
